### ISSUE TITLE
Update to Php 7.3

### ISSUE THREAD

**Issue by panosru** [php-censor/docker-php-censor#43]
I changed `
FROM php:7.1-fpm-alpine` and `
FROM php:7.1-fpm` to 
`FROM php:7.3-fpm-alpine` and `
FROM php:7.3-fpm` accordingly but when I run `php --version` in `docker exec -ti ci_worker_1 sh` I'm getting:

![image](https://user-images.githubusercontent.com/400362/50194882-8590d900-0345-11e9-83b4-8ae4576e88ee.png)

Thanks

**Comment by corpsee** [comment]
@panosru If you change image's `Dockerfile` you should run `docker-compose` with your own image instead of image from DockerHub.

```yml
version: '2.1'
services:
  web:
    image: "./web"
```

**Comment by panosru** [comment]
😵 How in the world I missed that...??

I literally didn't even bothered to check the docker-compose.yml file since I saw the folders and I was literally 100% sure that you had already set the image path to the folders 😂

```yml
version: '2.1'
services:
  web:
    build:
      context: ./web/
```

Anyways thanks!


PS: Видимо нужно ночью лучше спать потомучто голова не варит по начам.. Спасибо!
